// Auto-generated typography constants from Figma
// Do not edit this file manually
// Generated at: 2025-09-19T03:08:57.228Z

export const TYPOGRAPHY = {
  fontFamily: {
    inter: ['Inter', 'serif'],
  },

  heading: {
    h6: {
      fontSize: '20px',
      fontWeight: 600,
      lineHeight: 1.2,
      fontFamily: 'Inter',
    },
    h5: {
      fontSize: '24px',
      fontWeight: 700,
      lineHeight: 1.2,
      fontFamily: 'Inter',
    },
    h3: {
      fontSize: '32px',
      fontWeight: 500,
      lineHeight: 1.2,
      fontFamily: 'Inter',
    },
    h1: {
      fontSize: '64px',
      fontWeight: 500,
      lineHeight: 1.2,
      fontFamily: 'Inter',
    },
    h2: {
      fontSize: '48px',
      fontWeight: 500,
      lineHeight: 1.2,
      fontFamily: 'Inter',
    },
    h4: {
      fontSize: '28px',
      fontWeight: 700,
      lineHeight: 1.2,
      fontFamily: 'Inter',
    },
  },

  body: {
    'sm-semibold': {
      fontSize: '12px',
      fontWeight: 600,
      lineHeight: 1.4,
      fontFamily: 'Inter',
    },
    'xl-medium': {
      fontSize: '18px',
      fontWeight: 500,
      lineHeight: 1.5,
      fontFamily: 'Inter',
    },
    lg: {
      fontSize: '16px',
      fontWeight: 400,
      lineHeight: 1.5,
      fontFamily: 'Inter',
    },
    'base-semibold': {
      fontSize: '14px',
      fontWeight: 600,
      lineHeight: 1.5,
      fontFamily: 'Inter',
    },
    base: {
      fontSize: '14px',
      fontWeight: 400,
      lineHeight: 1.5,
      fontFamily: 'Inter',
    },
    'sm-medium': {
      fontSize: '12px',
      fontWeight: 500,
      lineHeight: 1.4,
      fontFamily: 'Inter',
    },
    'xl-semibold': {
      fontSize: '18px',
      fontWeight: 600,
      lineHeight: 1.5,
      fontFamily: 'Inter',
    },
    'lg-semibold': {
      fontSize: '16px',
      fontWeight: 600,
      lineHeight: 1.5,
      fontFamily: 'Inter',
    },
    xl: {
      fontSize: '18px',
      fontWeight: 400,
      lineHeight: 1.5,
      fontFamily: 'Inter',
    },
    'lg-medium': {
      fontSize: '16px',
      fontWeight: 500,
      lineHeight: 1.5,
      fontFamily: 'Inter',
    },
    sm: {
      fontSize: '12px',
      fontWeight: 400,
      lineHeight: 1.4,
      fontFamily: 'Inter',
    },
    'base-medium': {
      fontSize: '14px',
      fontWeight: 500,
      lineHeight: 1.5,
      fontFamily: 'Inter',
    },
  },
} as const

export type TypographyVariant = keyof typeof TYPOGRAPHY.heading | keyof typeof TYPOGRAPHY.body
