import { z } from 'zod'
import { RecruitmentChannelBelongTo } from '@/constants/api-schema-aliases'
/**
 * Zod schema for recruitment channel create form validation
 *
 * This schema defines validation rules for creating new recruitment channel
 * Note: code is auto-generated by backend, so not included in create form
 */
export const recruitmentChannelCreateSchema = z.object({
  name: z.string().min(1, 'Tên kênh là bắt buộc').max(250, 'Tên kênh không được quá 250 ký tự'),

  belong_to: z.nativeEnum(RecruitmentChannelBelongTo).optional(),

  description: z.string().min(1, 'Mô tả là bắt buộc').max(500, 'Mô tả không được quá 500 ký tự'),
})

export type RecruitmentChannelCreateFormData = z.infer<typeof recruitmentChannelCreateSchema>
